In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4],'float64') # Can also simply use float
print(a)
print(a.dtype)
b= np.array([1,2,3,4],'int64') # Can also simply use int
print(b)
print(b.dtype)

[ 1.  2.  3.  4.]
float64
[1 2 3 4]
int64


In [18]:
aa = np.array(range(10),float)
print(list(aa)) # covert back to list
bb = aa.reshape((2,5))
print(len(bb)) # the length of first axis, namely how many rows
print (2 in bb)
cc = list(bb) # convert back to list, but it is list of ndarray
print(cc)
dd = bb.tolist() # convert back to list
print(dd)

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
2
True
[array([ 0.,  1.,  2.,  3.,  4.]), array([ 5.,  6.,  7.,  8.,  9.])]
[[0.0, 1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0, 9.0]]


In [34]:
bb_s = bb.tostring() # Not readable, to easy to save large dataset in text
print(bb_s)
bb_back = np.fromstring(bb_s)
print(bb_back)
print(bb_back.shape)
bb_back = bb_back.reshape(2,5)
print(bb_back)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
(10,)
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [42]:
#Fill an ndarray with 1 number
bb_back1=bb_back.fill(0) 
print(bb_back)
print(bb_back1)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
None


In [40]:
cc = bb.transpose()
print(bb)
print(cc)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[[ 0.  5.]
 [ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]]


In [45]:
#Convert 2D array to 1D array
dd1 = bb.flatten()
print(dd1)
print(bb)
dd2 = cc.flatten()
print(dd2)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[ 0.  5.  1.  6.  2.  7.  3.  8.  4.  9.]


In [48]:
#Concatenate function
#1D array
a = np.array([1,2],float)
b = np.array([3,4,5,6],int)
c = np.array([7],float)
d = np.concatenate((a,b,c))
print(d)

[ 1.  2.  3.  4.  5.  6.  7.]


In [57]:
#2D Array
a = np.array([[1,2],[3,4]])
b = np.array([[4,5,6],[7,8,9]])
c = np.concatenate((a,b),axis = 1) # Concatenate by column
print(c)
#d = np.concatenate((a,b),axis = 0) This is error, 
#because a and b have different number of colunms

[[1 2 4 5 6]
 [3 4 7 8 9]]


In [65]:
#Add new dimension useing newaxis
a = np.array([1,2,3])
print(a.shape)
b = a[:,np.newaxis,np.newaxis]
c = a[np.newaxis,:,np.newaxis]
print (b.shape)
print(b)
print(c.shape)
print(a.shape)

(3,)
(3, 1, 1)
[[[1]]

 [[2]]

 [[3]]]
(1, 3, 1)
(3,)


In [67]:
#Other ways to create ndarray
a = np.arange(10)

In [71]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [79]:
np.eye(4,k = 1) # return matrix with ones along the kth diagonal

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [91]:
print(np.round(1.5))
print(np.rint(1.5))
print(np.floor(1.5))
print(np.ceil(1.5))
print(int(1.5))
print(round(1.5))
import math
print(math.ceil(1.5)) #No ceil function in base python
print(math.floor(1.5)) #No floor function in base python

2.0
2.0
1.0
2.0
1
2
2
1


In [95]:
#ndarray element wise calculation
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8])
print(a+b)
#print(b+c) Error dimension does not match 

[5 7 9]


In [110]:
b = np.array([[1,2,3],[4,5]]) #This is not a ndarray
print(b)
c = np.array([[1,2,3],[4,5,6]])
print(c)
d = np.array([[7,8,9],[7,8,9]])
print(d)
print (c+d)
d1 = np.array([[7,8],[7,9]])
# print(c+d1) error: dimension does not match 

[list([1, 2, 3]) list([4, 5])]
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [7 8 9]]
[[ 8 10 12]
 [11 13 15]]


In [127]:
#Broadcasting
a = np.array([[1,2],[3,4]])
b = np.array([10])
c = np.array([10,11])

In [128]:
print(a+b)
print(a+b[:,np.newaxis])
print(a+b[np.newaxis,:])
print(a+c)
print(a+c[:,np.newaxis])
print(a+c[np.newaxis,:])

[[11 12]
 [13 14]]
[[11 12]
 [13 14]]
[[11 12]
 [13 14]]
[[11 13]
 [13 15]]
[[11 12]
 [14 15]]
[[11 13]
 [13 15]]


In [130]:
a = np.array([[1,2],[3,4]])
b = np.array([10])
c = np.array([10,11,12])

In [134]:
print(a+b)
#print(a+c) Error, cannot concatenate
#print(a+c[:,np.newaxis]) Error, cannot concatenate 
#print(a+c[np.newaxis,:]) Error, cannot concatenate

[[11 12]
 [13 14]]


In [2]:
#Array iteratoin is the same as you treat array as list of list

In [3]:
#One interesting point
a = np.array([[1,2,3],[3,4,5]])

In [4]:
for x,y,z in a:
    print(x,y,z)

1 2 3
3 4 5


In [5]:
#If it is list of list, also works
a = [[1,2,3],[3,4,5]]
for x,y,z in a:
    print(x,y,z)

1 2 3
3 4 5


In [6]:
#clip function
a = np.array([[1,2,3],[3,4,5]])
a.clip(2,4) 

array([[2, 2, 3],
       [3, 4, 4]])

In [7]:
np.unique(a)

array([1, 2, 3, 4, 5])

In [8]:
a.diagonal()

array([1, 4])

In [9]:
#any() and all() function for bool array
c = np.array([True, False, False])

In [10]:
any(c)

True

In [11]:
all(c)

False

In [14]:
a = np.array([0,2])
a.nonzero()

(array([1]),)

In [18]:
a = np.array([1,np.NaN, np.Inf, -np.Inf])

In [19]:
np.isnan(a)

array([False,  True, False, False], dtype=bool)

In [20]:
np.isfinite(a)

array([ True, False, False, False], dtype=bool)

In [32]:
a = 1 + 2j
b = 2 + 3j
c = a + b
d = a*b
e = a/b

In [30]:
print(a)
print(c)
print(d)
print(e)

(1+2j)
(3+5j)
(-4+7j)
(0.6153846153846154+0.07692307692307691j)


In [33]:
a = np.array([[1,2,1,3],[5,3,1,8]],float)

In [36]:
np.corrcoef(a)

array([[ 1.        ,  0.72870505],
       [ 0.72870505,  1.        ]])

In [41]:
help(np.sum)

Help on function sum in module numpy.core.fromnumeric:

sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  I