In [2]:
import time
import numpy as np

In [6]:
x=np.random.random(100000000)
print(x.shape)
print(type(x))
y = x.reshape((100000000,1))
print(y.shape)
print(type(y))

(100000000,)
<class 'numpy.ndarray'>
(100000000, 1)
<class 'numpy.ndarray'>


In [9]:
print(np.dot(x,x)) #x is a 1d array. Can be treated as both a column vector and a row vector. It is flexible.
#print(np.dot(y,y)) #y is a 2D array.

33331404.5829


In [4]:
start = time.time()
sum(x)/len(x)
print time.time()-start

9.32835817337


In [5]:
start = time.time()
np.mean(x)
print time.time()-start

0.0721430778503


In [51]:
y=np.array([1,2,3,4])
y1=np.array([[1,2,3,4]])
z=np.array([[1,2,3,4],[5,6,7,8]])

In [52]:
print(type(y))
print(y.shape)
print(type(y1))
print(y1.shape)
print(type(z))
print(z.shape)

<class 'numpy.ndarray'>
(4,)
<class 'numpy.ndarray'>
(1, 4)
<class 'numpy.ndarray'>
(2, 4)


In [53]:
print(np.dot(z,y)) # y can be treated as a column vector. 
print(np.dot(z,y).shape)

[30 70]
(2,)


In [54]:
y=np.array([1,2])
y.shape
print(np.dot(y,z)) # y can be treated as a row vector
print(np.dot(y,z).shape)

[11 14 17 20]
(4,)


In [27]:
np.save('mymatrix', z)

In [28]:
z1=np.load('mymatrix.npy')
z1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
xx=np.zeros((3,4),dtype='int32')
print (xx)
print(xx.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)


In [55]:
yy=np.arange(0,3.0,1.6)
print(yy)
print(yy.shape)
print(yy.reshape(2,1))
print(yy.dtype)

[ 0.   1.6]
(2,)
[[ 0. ]
 [ 1.6]]
float64


In [57]:
yy=np.linspace(0,2,3)
print(yy)
print(yy.shape)
print(yy.dtype)

[ 0.  1.  2.]
(3,)
float64


In [63]:
x=np.random.normal(0,0.1,(5,5))

In [66]:
print (x)
print(x.shape)
print(x.sum())
print(x.mean())

[[ 0.00704435 -0.00455138  0.00040049  0.07750823  0.1694037 ]
 [-0.26850763 -0.06775095 -0.10796911  0.01420415  0.0321296 ]
 [-0.027579    0.00904359 -0.10254066 -0.05273357  0.03899523]
 [-0.08079524 -0.07257549 -0.01731809  0.04178829 -0.05836032]
 [-0.1450246  -0.04062728  0.182834   -0.01691438 -0.18899238]]
(5, 5)
-0.678888476144
-0.0271555390458


In [72]:
print(x[:,1].sum())
#print(x[,1].sum()) invalid syntax, must have :
print(x[1,].sum())
print(x[1,:].sum())
print(x[1].sum())

-0.176461519174
-0.397893951555
-0.397893951555
-0.397893951555


In [78]:
print(x<0)
(x<0).sum()

[[False  True False False False]
 [ True  True  True False False]
 [ True False  True  True False]
 [ True  True  True False  True]
 [ True  True False  True  True]]


15

In [77]:
print(x>0)
(x>=0).sum()

[[ True False  True  True  True]
 [False False False  True  True]
 [False  True False False  True]
 [False False False  True False]
 [False False  True False False]]


10

In [79]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

# We print X

print ('X = \n', X) 

# We print the unique elements of X 
print ('The unique elements in X are:',np.unique(X))
print (np.unique(X).shape)

X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]
The unique elements in X are: [1 2 3 5 8]
(5,)


In [81]:
x=np.random.randint(1,11,size=3)
print(x)
y=np.random.randint(1,11,size = (5,5))
print(y)

[6 8 3]
[[ 8 10  4  7  3]
 [ 7  5  3 10  8]
 [ 2  7  7  9 10]
 [ 7  3  1  1  5]
 [ 7  4  7  3  9]]


In [82]:
x=np.ones((4,4))
print (x)
print(x.dtype)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
float64
